### ISSUE TITLE
Invalid Syntax Error (Then statement)

### ISSUE THREAD

**Issue by NigelIWhite** [amaurycarvalho/msxbas2rom#1]
The following will generate a Syntax Error during compilation, but is valid syntax:

IF A=1 THEN 900

Changing the code to:

IF A=1 THEN GOTO 900

enables successful compilation but shouldn't be required as MSX-BASIC allows the GOTO to be omitted (the omission also results in faster [interpreted] code execution).

**Comment by amaurycarvalho** [comment]
Thanks NigelIWhite for your feedback!

When you compile your program to the **pcode interpreted ROM format** using MSXBAS2ROM this problem really occurs, as in the example below:

```
10 INPUT "VALUE";A
20 IF A=1 THEN 50
30 PRINT "VALUE <> 1"
40 END
50 PRINT "VALUE = 1"
```

As a preliminary workaround I will recommend you to try to compile your program to the **binary assembly ROM format** instead - by using "-c" parameter at command line - just as explained in the [Getting started](Gettingstarted) Wiki section.

I will fix this pcode conversion problem of interpreted mode on the next release anyway.

Thanks again for testing MSXBAS2ROM!
