### ISSUE TITLE
IF clause not working properly with logical test 

### ISSUE THREAD

**Issue by djogopatrao** [amaurycarvalho/msxbas2rom#5]
PROBLEM:

In the following code, the IF clause in line 2010 fails to fail when the specified condition is met.

SIMULATING:

The following piece of code, when compiled with msxbas2rom -c (version 0.2.9.8) is supposed to enter line 2015 and beep whenever the cursor enters a new region of the screen. It should only beep once, as variables xi and xj are updated. The cursor moves when using the arrow keys.

However:
1) if you start by going down, It will not enter the routine
2) if you start by going right, it will always enter the routine (making it beep continuously, even if you are not moving the cursor)

by commenting line 105, the program behaves differently but still not correctly. The same by commenting 1050-1130.

```

5 defint a-z
10 SCREEN 1,2,0
20 WIDTH 32
30 KEYOFF
40 COLOR 15,14,14

65 sprite$(0)=string$(8,255)


90 CLS

100 x=0:y=0
105 gosub 1000

110 putsprite 0,(x,y),15,0
120 gosub 2000

900 st=stick(0): if st = 0 then 990
910 if st=8 or st<3 then y=y-1
920 if st>1 and st<5 then x=x+1
930 if st>3 and st<7 then y=y+1
940 if st>5 then x=x-1

990 goto 110	

1000 xi=int(x/8):yi=int(y/8)

1010 x1=xi-5: if x1<0  then x1=0
1020 y1=yi-5: if y1<0  then y1=0
1030 x2=xi+5: if x2>19 then x2=19
1040 y2=yi+5: if y2>19 then y2=19

1050 cls
1060 for i=y1 to y2
1070 	locate x1,i
1090	for j=x1 to x2
1100		print "!";
1120	next j
1130 next i
1140 return

2000 xj=int(x/8):yj=int(y/8)
2005 locate 20, 0:print xi;yi;xj;yj
2006 locate 20, 1:print xi=xj;yi=yj;(xi=xj) and (yi=yj)
2010 if (xi=xj) and (yi=jy) then 2900
2015 beep

2020 x3=xj-5: if x3<0  then x3=0
2030 y3=yj-5: if y3<0  then y3=0
2040 x4=xj+5: if x4>19 then x4=19
2050 y4=yj+5: if y4>19 then y4=19

2800 x1=x3:y1=y3
2810 x2=x4:y2=y4
2820 xi=xj:yi=yj

2900 return
```

**Comment by amaurycarvalho** [comment]
There was a typo on the code, where a reference to a wrong variable name was written on the line 2010 ("jy" instead of "yj").
