### ISSUE TITLE
Issues with tiles on screen 4 (and possibly screen2)

### ISSUE THREAD

**Issue by djogopatrao** [amaurycarvalho/msxbas2rom#6]
The code attached was tested on both msxbas2rom 0.3.0.0 and 0.3.0.1, both showed the same problems.

`
10 SCREEN 4
20 bload "teste.sc2",s
30 a$=input$(1)

' the line below works for screen4, but base(10) is meant for screen2
40 FOR I = 0 TO 767: VPOKE BASE(10)+I,255:NEXT I
45 a$=input$(1)

' this is the same as above, but replacing base(10) with (20) which is the
' correct for screen4, but does not work (screen does not change)
50 FOR I = 0 TO 767: VPOKE BASE(20)+I,1:NEXT I
55 a$=input$(1)

' put tile starts at somewhere in the middle of the first third of screen,
' not the top left corner
60 FOR I = 0 TO 767: PUT TILE 2, ( i mod 32, i \ 32 ):NEXT I
65 a$=input$(1)
`

**Comment by djogopatrao** [comment]
[bug_msxbas2rom.zip](https://github.com/amaurycarvalho/msxbas2rom/files/11642510/bug_msxbas2rom.zip)
of course I forgot the attachment =)

after loading the ROM we get the screen below:

![image](https://github.com/amaurycarvalho/msxbas2rom/assets/3697549/18252a67-eb9f-44b0-b80a-1bd9204dd93a)

we press enter and it runs the line 40, erasing the screen (filling with tile 255 which is empty)

![image](https://github.com/amaurycarvalho/msxbas2rom/assets/3697549/db7cb4b5-b962-4114-bc64-6b906450ce33)

another enter and the screen is still empty

next enter, and the bug in put tile (line 60) is shown

![image](https://github.com/amaurycarvalho/msxbas2rom/assets/3697549/6ba29955-f3de-4f87-8e01-486ea1f139af)

**Comment by djogopatrao** [comment]
running it on the bios basic.

line 50 produces the expected result:

![image](https://github.com/amaurycarvalho/msxbas2rom/assets/3697549/03cda9fb-b13c-420e-81fe-b7e4bc9503d0)

line 60 does not apply, as put tile is not implemented on bios basic

**Comment by amaurycarvalho** [comment]
This BASE function bug was solved in [release v0.3.0.8](https://github.com/amaurycarvalho/msxbas2rom/releases/tag/v0.3.0.8).

Relating to "PUT TILE", screens 2 and 4 initializes in graphical mode by default. To use tiled mode instructions (like PRINT and PUT TILE), you'll need to include "SET TILE ON" after you change the screen mode, just like that:

```
10 SCREEN 4
15 SET TILE ON
20 bload "teste.sc2",s
```
